Тебе удалось узнать, как обрабатывать исключения. Часто нужно выполнить какое-то действие в любом случае: не важно, произошёл сбой или нет.

Например, нужно закрыть файл в конце программы. Если этого не сделать, к нему не получится обратиться ещё раз, потому что файл будет «занят».

Поможет ключевое слово `finally`. С его помощью можно добавить действие, которое запустится в любом случае — не важно, появится исключение или нет.

Например, в этой программе код в блоке `finally` выполнится после действий в `try...catch`**:**
```
try {
    // действие, которое может вызвать ошибку
} catch (Exception exception) {
    // обработка исключения, если оно появится
} finally {
    // действие, которое должно вызываться всегда
} 
```

В блок `finally` зашито действие: в консоли появляется текст `"Этот код выполняется вне зависимости от произошедшего"`.

Если указать неверный путь до файла, программа отловит исключение. Сначала появится сообщение об ошибке из блока `catch`, а потом — сообщение из блока `finally`:
```
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.io.IOException;
import java.nio.file.NoSuchFileException;

public class Praktikum {

    public static void main(String[] args) {
        try {
            Files.lines(Paths.get("C:\\Praktikum.txt"), StandardCharsets.UTF_8).forEach(System.out::println);
        } catch (NoSuchFileException exception) {
            System.out.println("Файл не найден");
        } catch (IOException exception) {
            System.out.println("Неизвестная ошибка");
        } finally {
            System.out.println("Этот код выполняется вне зависимости от произошедшего");
        }
    }

} 
```

### Ключевое слово `throws`

Слово `throws` сообщает, что метод или конструктор может сгенерировать исключение. `catch` обрабатывает исключения, а `throws` просто предупреждает о них.

Его нужно написать после параметров метода:
```
public void methodWithException() throws CheckedException { // показывает, что в коде может быть исключение CheckedException
    // код программы
   
```

Это ключевое слово нужно отличать от другого — `throw`.

`throw` понадобится, когда нужно выбросить исключение. `throws` же говорит лишь о возможности исключения, но оно может никогда не возникнуть.
```
public void methodWithException() throws CheckedException { // показывает, что в коде может быть исключение CheckedException
    // код программы
    if (someCondition) { // при определённом условии
        throw new CheckedException(); // код выдаст исключение CheckedException
    }
    // ещё код
} 
```

Можно описать несколько ошибок сразу. Например, когда пользователь не ввёл символы в пароле или ввёл слишком много.

Нужно перечислить названия ошибок через запятую:
```
public void methodWithMultipleExceptions() throws FirstCheckedException, SecondCheckedException {
    // код
    if (someCondition) {
        throw new FirstCheckedException();
    }
    // код
    if (someCondition) {
        throw new SecondCheckedException();
    }
    // код
} 
```

### Забери с собой

Вот и всё. Чтобы повторить всё про исключения, загляни в [шпаргалку](https://code.s3.yandex.net/qa-automation-engineer/java/track2/cheatsheets/sprint5/exceptions_cheatsheet.pdf).

### Задание
#### 1
Потренируйся использовать `finally` без `catch`. Проверь, как обработается непроверяемое исключение `NullPointerException`.

Оберни код внутри метода в блок `try`. Добавь блок `finally`: в нём будет выводиться текст `"Этот код выполняется вне зависимости от произошедшего"`.

После блока `try...finally` добавь вывод сообщения `"Завершение программы"`.
Без решения
```Java
public class Praktikum {

    public static void main(String[] args) {
        String string = null;
        string.length();
        System.out.println("Код отработал без ошибок");
    }

}
```

С решением
```Java

```
